In [1]:
import numpy as np

In [2]:
import time

In [3]:
x = np.random.random(100000000)

In [4]:
start = time.time()
sum(x)/len(x)
print(time.time() - start)

20.43139958381653


In [5]:
start = time.time()
np.mean(x)
print(time.time() - start)

0.07001924514770508


In [6]:
t = np.array([1,2,3,4,5])

In [7]:
print(t , type(t),  t.dtype, t.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [8]:
t =  np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])

In [10]:
print(t , type(t),  t.dtype, t.shape)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]] <class 'numpy.ndarray'> int64 (4, 3)


In [11]:
t = np.array([1,'2',3,4,5])

In [13]:
print(t , type(t),  t.dtype, t.shape)

['1' '2' '3' '4' '5'] <class 'numpy.ndarray'> <U21 (5,)


In [14]:
t = np.array([1,2.0,3,4,5])

In [15]:
print(t , type(t),  t.dtype, t.shape)

[1. 2. 3. 4. 5.] <class 'numpy.ndarray'> float64 (5,)


In [17]:
t = np.array([1.5,2.2,3.5,4.6,5.7],dtype='int64')

In [19]:
print(t , type(t),  t.dtype, t.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [20]:
t = np.array([1.5,2.2,3.5,4.6,5.7],dtype=np.int64)

In [21]:
print(t , type(t),  t.dtype, t.shape)

[1 2 3 4 5] <class 'numpy.ndarray'> int64 (5,)


In [22]:
# save arraay in file

In [24]:
np.save('my_array',t)

In [25]:
#load file

In [26]:
np.load('my_array.npy')

array([1, 2, 3, 4, 5])