In [4]:
import numpy as np

In [5]:
x = np.zeros((3,4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


In [8]:
x = np.ones((4,5))
print(x)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [9]:
x = np.ones((4,5),dtype=int)
print(x)

[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]


In [10]:
x = np.full((4,3),5)
print(x)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]


In [11]:
x = np.eye(5)
print(x)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [13]:
x = np.diag([5,10,20,30])
print(x)

[[ 5  0  0  0]
 [ 0 10  0  0]
 [ 0  0 20  0]
 [ 0  0  0 30]]


In [14]:
x = np.arange(5)
print(x)

[0 1 2 3 4]


In [15]:
x = np.arange(5,10)
print(x)

[5 6 7 8 9]


In [16]:
x = np.arange(0,11,2)
print(x)

[ 0  2  4  6  8 10]


In [17]:
x = np.linspace(0,25,10)
print(x)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]


In [18]:
x = np.linspace(0,25,10,endpoint=False)
print(x)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]


In [19]:
x = np.arange(20)
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [21]:
x = np.reshape(x,(4,5))
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [22]:
x = np.reshape(x,(10,2))
print(x)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]


In [29]:
x = np.arange(20).reshape(4,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [25]:
x = np.linspace(0,25,10,endpoint=False).reshape(2,5)
print(x)

[[ 0.   2.5  5.   7.5 10. ]
 [12.5 15.  17.5 20.  22.5]]


In [30]:
x = np.random.random((3,3))
print(x)

[[0.71711654 0.99808643 0.87207182]
 [0.02644479 0.08674962 0.88829137]
 [0.94564028 0.82380257 0.90289648]]


In [31]:
x = np.random.randint(1,10,(3,3))
print(x)

[[6 6 8]
 [2 5 2]
 [2 9 3]]


In [34]:
X = np.random.normal(0,1,size=(1000,1000))
print(x)

[[-0.94293955 -1.32738571  1.52870384 ...  1.09465711  0.55263855
  -0.45620669]
 [ 0.25651372 -1.27106651 -0.58271595 ... -1.93823074  1.80064179
  -1.42897789]
 [-0.63775273  2.53165262  0.14187278 ...  1.02737906 -0.56453114
  -0.97514924]
 ...
 [ 0.89925206 -1.38920772 -2.06161806 ... -0.56899728  0.30895827
  -1.01957385]
 [ 0.8165636  -0.27308964  0.67774544 ...  0.41661397  1.18247868
   0.88919343]
 [ 0.78088779  0.06446616  0.58488702 ... -1.4122987   0.07766838
   1.29595582]]


In [39]:
print('Mean:',X.mean())
print('Std:',X.std())
print('Min:',X.min())
print('Max:',X.max())
print('# positive:',(X > 0).sum())
print('# negative:',(X < 0).sum())




Mean: 0.0003018954087225307
Std: 0.9983040738737168
Min: -4.542916087905943
Max: 4.865319754443216
# positive: 499738
# negative: 500262
