In [1]:
import numpy as np
import jovian

<IPython.core.display.Javascript object>

In [2]:
x = np.arange(25).reshape(5,5)
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [3]:
# boolean index manipulation:

In [4]:
print(x|x>10)

[[False False False False False]
 [False False False False False]
 [False  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [5]:
print(x[x>10])

[11 12 13 14 15 16 17 18 19 20 21 22 23 24]


In [6]:
print(x[x<=7])

[0 1 2 3 4 5 6 7]


In [7]:
print(x[(x>10) & (x<=17)])

[11 12 13 14 15 16 17]


In [8]:
#assign elt between 11 and 17 to -1

In [9]:
x[(x>10) & (x<=17)]=-1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 -1 -1 -1 -1]
 [-1 -1 -1 18 19]
 [20 21 22 23 24]]


In [10]:
#set operations

In [11]:
x = np.array([1,2,3,4,5])
y = np.array([6,7,2,8,4])

print(np.intersect1d(x,y))
print(np.setdiff1d(x,y))
print(np.union1d(x,y))

[2 4]
[1 3 5]
[1 2 3 4 5 6 7 8]


In [12]:
x =np.random.randint(1,11,size=(10,))
print(x)

[9 2 8 1 2 7 8 2 1 3]


In [13]:
#sort operation

In [14]:
#x not change
print(np.sort(x))
print(x)

[1 1 2 2 2 3 7 8 8 9]
[9 2 8 1 2 7 8 2 1 3]


In [15]:
#x change
x.sort()
print(x)

[1 1 2 2 2 3 7 8 8 9]


In [16]:
# sorting by row or by colunm

In [17]:
x =np.random.randint(1,11,size=(5,5))
print(x)


[[ 7  4  8  7  3]
 [ 9  1  7  7  5]
 [ 3  5  1  3  2]
 [ 7 10  7  3  7]
 [ 2  9  1  4 10]]


In [18]:
print('sort by x axis or by column\n',np.sort(x,axis=0))

sort by x axis or by column
 [[ 2  1  1  3  2]
 [ 3  4  1  3  3]
 [ 7  5  7  4  5]
 [ 7  9  7  7  7]
 [ 9 10  8  7 10]]


In [19]:
print('sort by y axis or by row\n',np.sort(x,axis=1))

sort by y axis or by row
 [[ 3  4  7  7  8]
 [ 1  5  7  7  9]
 [ 1  2  3  3  5]
 [ 3  7  7  7 10]
 [ 1  2  4  9 10]]


In [ ]:
jovian.commit()

<IPython.core.display.Javascript object>

[jovian] Attempting to save notebook..
